[package]
name = "kingen_elias2012/create-80ct---professional-minecraft-server-website (3) BACKUP"
version = "0.1.0"
description = "Stable smp"

[[module]]
name = "spy-game"
source = "."
abi = "wasi"

[module.interface.wasi]
main-args = ["server.js"]

[[command]]
name = "server"
module = "spy-game"
runner = "wasi"

[deploy]
app_name = "spy-game"
