[package]
name = "kingen_elias2012/minecraft-website"
version = "0.1.0"
description = "Stable SMP - Professional Minecraft Server Website"

[[module]]
name = "static"
source = "."

[[command]]
name = "server"
module = "static"
runner = "https://webc.org/runner/static"

[deploy]
app_name = "minecraft-website"
